# Generated by Django 5.0.2 on 2024-03-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact_category_view_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
